name: Build and Push Docker Images
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 1"
  push:
    branches:
      - '*'
    paths:
      - Dockerfile

jobs:
  push:
    name: "Build and Push Docker Image for ${{ matrix.branch }}"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        branch: 
          - 'v1.11.5'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.REGISTRY_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./${{ matrix.branch }}/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ghcr.io/BlueprintFramework/blueprint:${{ matrix.branch }}
